# Generated by Django 5.2.8 on 2025-12-15 17:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKU', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('subcategoria', models.CharField(blank=True, max_length=50, null=True)),
                ('variante', models.CharField(blank=True, max_length=50, null=True)),
                ('total_vendidos', models.IntegerField(default=0)),
                ('imagen_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('tipo_cliente', models.CharField(choices=[('Persona', 'Persona'), ('Empresa', 'Empresa')], max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('subtotal_carrito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='carritos', to='project_core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('estado_pedido', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos', to='project_core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50)),
                ('cedula_cliente', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion_cliente', models.TextField(blank=True, null=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('Tarjeta de crédito', 'Tarjeta de crédito'), ('Tarjeta de débito', 'Tarjeta de débito'), ('Cheque', 'Cheque')], max_length=20, null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('url_factura', models.URLField(blank=True, null=True)),
                ('estado_fiscal', models.CharField(blank=True, choices=[('Emitido', 'Emitido'), ('Cancelado', 'Cancelado'), ('Pendiente', 'Pendiente'), ('Reembolsado', 'Reembolsado')], max_length=20, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='project_core.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pvm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='project_core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('ubicacion_bodega', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favoritos_cliente', to='project_core.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favoritos_cliente', to='project_core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_detalle_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_detalle_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_detalle_pedido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_detalle_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='project_core.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal_detalle_carrito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva_detalle_carrito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento_detalle_carrito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_detalle_carrito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_carrito', to='project_core.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('numero_guia', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_entrega', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Preparando', 'Preparando'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado')], max_length=20)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_core.pedido')),
            ],
        ),
    ]
