# Generated by Django 5.2.8 on 2025-12-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caracteristica1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristica2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristica3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristica4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristica5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
