# Generated by Django 5.2.8 on 2025-12-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0002_producto_caracteristica1_producto_caracteristica2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
