# Generated by Django 5.2.8 on 2025-11-30 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0003_alter_detallepedido_precio_unitario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50)),
                ('cedula_cliente', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion_cliente', models.TextField(blank=True, null=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('Tarjeta de crédito', 'Tarjeta de crédito'), ('Tarjeta de débito', 'Tarjeta de débito'), ('Cheque', 'Cheque')], max_length=20, null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('url_factura', models.URLField(blank=True, null=True)),
                ('estado_fiscal', models.CharField(blank=True, choices=[('Emitido', 'Emitido'), ('Cancelado', 'Cancelado'), ('Pendiente', 'Pendiente'), ('Reembolsado', 'Reembolsado')], max_length=20, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='project_core.pedido')),
            ],
        ),
    ]
