# Generated by Django 5.2.8 on 2025-12-10 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0004_cliente_user_detallepedido_iva_comprobante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='descuento',
            new_name='descuento_detalle_pedido',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='iva',
            new_name='iva_detalle_pedido',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='subtotal',
            new_name='subtotal_detalle_pedido',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='total',
            new_name='total_detalle_pedido',
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='project_core.pedido'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Convertido a pedido', 'Convertido a pedido'), ('Abandonado', 'Abandonado')], max_length=20)),
                ('subtotal_carrito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='carritos', to='project_core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal_detalle_carrito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento_detalle_carrito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_detalle_carrito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_carrito', to='project_core.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_core.producto')),
            ],
        ),
    ]
