# Generated by Django 5.2.8 on 2025-12-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0004_categoria_alter_producto_categoria_subcategoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='subtotal_carrito',
        ),
    ]
