# Generated by Django 5.2.8 on 2025-12-29 17:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0005_remove_carrito_subtotal_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='descuento_mayorista',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='precio',
            name='descuento_publico',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
