# Generated by Django 5.2.8 on 2025-12-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0005_rename_descuento_detallepedido_descuento_detalle_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='estado',
        ),
    ]
