# Generated by Django 5.2.8 on 2025-12-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0006_remove_carrito_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favoritos_cliente', to='project_core.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='favoritos_cliente', to='project_core.producto')),
            ],
        ),
    ]
