# Generated by Django 5.2.8 on 2025-12-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0006_precio_descuento_mayorista_precio_descuento_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecarrito',
            name='subtotal_antes_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
