# Generated by Django 5.2.8 on 2025-12-31 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0007_detallecarrito_subtotal_antes_descuento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritoscliente',
            unique_together={('cliente', 'producto')},
        ),
    ]
