# Generated by Django 5.2.8 on 2026-01-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0008_alter_favoritoscliente_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
