# Generated by Django 5.2.8 on 2026-01-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0010_preregistrouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='foto_categoria_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
