# Generated by Django 5.2.8 on 2026-01-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0012_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='URL_VALIDACION',
            field=models.URLField(blank=True, null=True),
        ),
    ]
