# Generated by Django 5.2.8 on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0013_cliente_url_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_cuenta',
            field=models.CharField(
                choices=[
                    ('ACTIVO', 'ACTIVO'),
                    ('PENDIENTE', 'PENDIENTE'),
                    ('INACTIVO', 'INACTIVO'),
                    ('ELIMINADO', 'ELIMINADO'),
                ],
                default='ACTIVO',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='preregistrouser',
            name='tipo_cliente',
            field=models.CharField(
                choices=[('Persona', 'Persona'), ('Empresa', 'Empresa')],
                default='Persona',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='preregistrouser',
            name='url_validacion',
            field=models.URLField(blank=True, null=True),
        ),
    ]



