# Generated by Django 5.2.8 on 2026-01-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0014_cliente_estado_cuenta_preregistro_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='URL_VALIDACION',
            new_name='url_validacion',
        ),
    ]


