# Generated by Django 5.2.8 on 2026-01-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0015_rename_cliente_url_validacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='cedula_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
