# Generated by Django 5.2.8 on 2026-01-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0022_comprobante_transferencia_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_transferencia',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes_transferencia/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En revisión', 'En revisión'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], max_length=20),
        ),
    ]
